language: perl
os:
  - linux
perl:
  - '5.20'
  - '5.18'
  - '5.16'
  - '5.14'
  - '5.12'
  - '5.10'
install:
  - provision/travis.sh
script:
  - perl Makefile.PL
  - make
  - make test
  - make dist
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Xnmab8XGFv2zR8OyszOeRxibYr9c3gavRyPokEPMkscOljamS9Uy0yYJ5x0sUWWozq6Dd1cg5Mkef7GG7tgSCqV+Fu57lpz4aHGu2OpnIsKGwrMDhNsS4qOYbEGpcIiE0YKRtIiGiJmK6kr8lmbCI8fdQakbW/7vZW1a1a154Aw=
  file_glob: true
  file: EV-Tarantool*.tar.gz
  on:
    tags: true
notifications:
  email: true
sudo: required
