sudo: false
language: C
services:
  - docker

cache:
  directories:
    - $HOME/.cache

env:
  global:
    - PRODUCT=EV-Tarantool16
    - ARCH=x86_64
  matrix:
    - OS=el DIST=7 VAR_TARANTOOL=1.6
    - OS=el DIST=7 VAR_TARANTOOL=1.7
    - OS=el DIST=7 VAR_TARANTOOL=1.9

script:
  - git describe --long
  - git clone -b prebuild_fixes https://github.com/igorcoding/packpack.git packpack
  - packpack/packpack

before_deploy:
  - ls -l build/

deploy:
  # Deploy packages to PackageCloud
  - provider: packagecloud
    username: igorcoding
    repository: "tarantoolcontrib"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}" && "${VAR_TARANTOOL}" = "1.9"

notifications:
  email: true
