--- #YAML:1.0
name:               EV-Tarantool16
version:            0.01
abstract:           Perl extension for Tarantool 1.6
author:
	- Mons Anderson <mons@cpan.org>
    - igorcoding <igorcoding@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    EV:  4
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
